---
title: "Research"
output: html_document
---

# Working Paper

#### **Fire Sale Risk and Mortgage Origination**, with D.Bongaerts and W.Wagner, 2020

Abstract: This paper empirically examines the anticipation of disorderly collateral liquidations into mortgage lending decisions in the United States. In line with previous literature on endogenous fire-sales, we document that lenders' incentives to supply credit decrease in their portfolio similarity with other market participants and in the dispersion of mortgages surrounding the collateral. Crucially, all effects are shown to weaken in markets where foreclosures are subject to higher frictions, and hence where fire-sale risk is less relevant to begin with. We further support the results finding a stronger effect for balance sheet-constrained lenders and exploiting plausibly exogenous shocks from large bank mergers. We find little evidence that lenders charge interest rates accordingly. The anticipation of fire-sale risk has consequences for overall credit, as lenders divert capital away from prone-to-fire sales markets, improving financial stability going forward.

#### **Closed For Business**, with D.Bongaerts and W.Wagner, 2020

Abstract: We investigate the effectiveness of business shutdowns to contain the Covid-19 disease. In March 2020, Italy shut down operations in a number of sectors. Using a difference-in-difference approach, we find that municipalities
with higher exposure to closed sectors experience subsequently lower mortality rates. We estimate the resulting life savings to exceed 12.000 people over less than a month. Using estimates of remaining life-years, this translates
into monetary benefits of 12 billion Euros We also show that business shutdowns exhibit rapidly diminishing returns and generate spillover effects outside the closed sectors as well as in other municipalities. This suggests that effective containment policies require central coordination.

# Work in progress

#### **Macroprudential Tax on Debt**, with A. Silva, 2018

#### **The drivers of Digital Innovation in Banking**, Financial Stability - Bank of Italy, 2018
 
